INSERT INTO EXCHANGE_VALUE (ID, CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,PORT) VALUES
(1001,'USD','IND',65,0);
INSERT INTO EXCHANGE_VALUE (ID, CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,PORT) VALUES
(1002,'EUR','IND',75,0);
INSERT INTO EXCHANGE_VALUE (ID, CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,PORT) VALUES
(1003,'CAD','IND',64,0);